blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('article/<str:slang>/', views.article, name='article'),
    path('category/<str:slang>/', views.category, name='category'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('search/', views.search, name='search'),

    path('create_post/', views.create_post, name='create_post'),
    path('update_post/<str:slang>/', views.update_post, name='update_post'),
    path('delete_post/<str:slang>/', views.delete_post, name='delete_post'),

    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('email_verification_sent/', views.email_verification_sent, name='email_verification_sent'),

    path('comment/<int:pk>', views.add_comment, name='comment'),
    path('update_profile_pic/', views.update_profile_pic, name='update_profile_pic'),
    path('hit_like/<int:pk>', views.hit_like, name='hit_like'),
    path('hit_like/', views.like, name='hit_like'),

]

readit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

    #password reset urls
    path(r'password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path(r'password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path(r'password_reset/', auth_views.PasswordResetView.as_view(template_name='blog/password_reset.html'),
         name='password_reset'),
    path(r'password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='blog/password_reset_done.html'),
         name='password_reset_done'),
    path(r'password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/login',
        template_name='blog/password_reset_confirm.html'), name='password_reset_confirm'),
    path(r'password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete'),
         name='password_reset_complete'),

    # Email verification urls
    path('verification/', include('verify_email.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django.contrib.auth.models import User

from ckeditor.fields import RichTextField
# Create your models here.

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    profile_pic = models.ImageField(null=True, blank=True, default='image/placeholder.png')

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    body = RichTextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    category = models.ManyToManyField(Category)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    slang = models.CharField(null=True, blank=True, max_length=200)

    def __str__(self):
        return self.title

class Comment(models.Model):
    author = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=200)
    like = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return self.comment_text

    def total_likes(self):
        likes = self.likes_set.all()
        total_likes = likes.count()
        return total_likes

class Likes(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    like = models.BooleanField(default=False)

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import *

class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'body', 'category', 'slang']
        widgets = {'title': forms.TextInput(attrs={'class': 'form-control custom-input'}),
                   'slang': forms.TextInput(attrs={'placeholder': "use ' _ ' instead of spaces "})
                   }

class CustomUserCreationForm(forms.Form):
    first_name = forms.CharField(label="First Name", min_length=4, max_length=50,
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label="Last Name", min_length=4, max_length=50,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(label="Username", min_length=4, max_length=150,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="Enter Email", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        return last_name

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError("Username already Exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

class UserProfilePicForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['profile_pic']

blog/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, reverse, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm

from verify_email.email_handler import send_verification_email

from .decorators import *
import datetime
import json

from .forms import *
from .models import *
# Create your views here.

date = datetime.datetime.now()
date = date.strftime("%Y/%m/%d")

def index(request):
    posts = get_list_or_404(Post)
    categories = Category.objects.all()
    context = {
        'posts': posts,
        'categories': categories
    }
    return render(request, 'blog/index.html', context)

def article(request, slang):
    post = get_object_or_404(Post, slang=slang)
    post_id=post.id
    date_created = post.date_created
    comments = Comment.objects.filter(post=post_id)

    context = {
        'date_created': date_created,
        'post': post,
        'comments': comments,
    }
    return render(request, 'blog/content.html', context)

def category(request, slang):
    categories = Category.objects.all()
    category_id = Category.objects.filter(name__contains=slang)[0].id
    posts = Post.objects.filter(category=category_id)
    context = {
        'slang':slang,
        'posts': posts,
        'categories': categories,
    }
    return render(request, 'blog/category.html', context)

def search(request):
    search = request.GET.get('search')
    search_result = Post.objects.filter(body__contains=search)
    print(search_result)
    context = {
        'search_keyword':search,
        'search_result':search_result,
    }
    return render(request, 'blog/search_result.html', context)

@login_required(login_url='blog:login')
def create_post(request):
    user = request.user
    form = PostCreationForm()
    if request.method == 'POST':
        form = PostCreationForm(request.POST, request.FILES)
        if form.is_valid():
           article = form.save()
           article.author = request.user
           article.save()
           return HttpResponseRedirect(reverse('blog:index'))
        else:
            print("invalid")
    context = {
        'form': form,
        'user': user,
        'date': date
    }
    return render(request, 'blog/create_post.html', context)

@login_required(login_url='blog:login')
def update_post(request, slang):
    post = Post.objects.get(slang=slang)
    form = PostCreationForm(instance=post)
    if request.method == 'POST':
        form = PostCreationForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('blog:dashboard'))
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'blog/update_post.html', context)

@login_required(login_url='blog:login')
def delete_post(request, slang):
    user = request.user
    post = Post.objects.get(slang=slang)
    groups = []
    for group in user.groups.all():
        groups.append(group.name)

    if 'admin' in groups:
        return HttpResponseRedirect(reverse("blog:admin_dashboard"))
    else:
        return HttpResponseRedirect(reverse('blog:dashboard'))

@login_required(login_url='blog:login')
@allowed_user(allowed_roles=['author'])
def dashboard(request):
    user = request.user
    posts = Post.objects.filter(author=user)
    total_posts = len(posts)
    categories = Category.objects.all()
    author = user.author
    form = UserProfilePicForm(instance=author)
    context = {
        'posts': posts,
        'total_posts': total_posts,
        'categories': categories,
        'form':form,
    }
    return render(request, 'blog/dashboard.html', context)

@login_required(login_url='blog:login')
@allowed_user(allowed_roles=['admin'])
def admin_dashboard(request):
    posts = Post.objects.all()
    total_posts = len(posts)
    categories = Category.objects.all()
    context = {
        'posts':posts,
        'total_posts': total_posts,
        'categories':categories,
    }
    return render(request, 'blog/admin_dashboard.html', context)

@unauthenticated_user
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            print("Authenticated")
            return HttpResponseRedirect(reverse('blog:index'))
        else:
            messages.error(request, "Invalid Credentials!!")
            return HttpResponseRedirect(reverse('blog:login'))
    return render(request, 'blog/login.html')

@unauthenticated_user
def register_view(request):
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = send_verification_email(request, form)
            user.first_name = form.clean_first_name()
            user.last_name = form.clean_last_name()
            user.save()
            user.groups.add(Group.objects.get(id=2))
            author = Author.objects.create(user=user)
            author.save()
            return HttpResponseRedirect(reverse('blog:email_verification_sent'))

    context = {
        'form': form
    }
    return render(request, 'blog/register.html', context)

def email_verification_sent(request):
    return render(request, 'blog/registration_email_sent.html')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:index'))

# comment Views

def add_comment(request, pk):
    if request.user.is_authenticated:
        username = request.user.username
        user = User.objects.filter(username=username)[0]
        post = Post.objects.get(id=pk)
        comment_text = request.POST['comment']
        print(user, post, comment_text)
        comment = Comment.objects.create(author=user, post=post, comment_text=comment_text)

        return HttpResponseRedirect(f'/article/{post.slang}')
    else:
        return HttpResponseRedirect(reverse('blog:login'))

def hit_like(request, pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(id=pk)
        post_slug = Post.objects.filter(comment=pk)[0].slang
        if Likes.objects.filter(author=request.user, comment=comment).exists():
            Likes.objects.filter(author=request.user, comment=comment)[0].delete()
            return redirect(f'/article/{post_slug}')
        else:
            like = Likes.objects.create(author=request.user, comment=comment)
            like.save()
    else:
        return redirect('blog:login')

    return redirect(f'/article/{post_slug}')

def update_profile_pic(request):
    if request.method == 'POST':
        author = request.user.author
        form = UserProfilePicForm(request.POST, request.FILES, instance=author)
        if form.is_valid():
            form.save()
            return redirect(reverse('blog:dashboard'))

    return redirect(reverse('blog:dashboard'))

def like(request):
    data = json.loads(request.body)
    commentId = data['commentId']
    comment = Comment.objects.get(id=commentId)
    if Likes.objects.filter(author=request.user, comment=comment).exists():
        Likes.objects.filter(author=request.user, comment=comment)[0].delete()
        total_likes = comment.total_likes()
        return JsonResponse(total_likes, safe=False)
    else:
        like = Likes.objects.create(author=request.user, comment=comment)
        like.save()
        total_likes = comment.total_likes()
        return JsonResponse(total_likes, safe=False)

blog/templates/blog/admin_dashboard.html
{% extends 'blog/main.html'%}
{% load static %}
{% block content %}
    <div class="outer-profile-container">
        <div class="inner-profile-container">
            <div class="profile-detail-container">
                <div class="profile-picture" style="background-image: url('./images/placeholder.png');">

                </div>
                <h2>{{user.username}}</h2>
                <h3>{{user.email}}</h3>
            </div>
            <div class="total-post">
                <h3>Total Posts</h3>
                <p>{{total_posts}}</p>
            </div>
            <div class="total-feedbacks">
                <h3>Total Feedbacks</h3>
                <p>80</p>
            </div>
        </div>
    </div>
    <div class="your-post">
        <h1>Your Posts</h1>
        {% for post in posts %}
        <div class="post-card">
            {% if post.image %}
            <div class="post-thumbnail" style="background-image: url('{{post.image.url}}');">

            </div>
            {% else %}
            <div class="post-thumbnail" style="background-image: url('');">

            </div>
            {% endif %}
            <div class="post-title">
                <p>{{post.title}}</p>
                <div class="buttons">
                    <a href="{% url 'blog:delete_post' post.slang %}" class="btn btn-outline-danger">Delete</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/content.html
{% extends 'blog/main.html'%}

{% load static %}

{% block content %}

    <section class="main-container">
        {% if post.image %}
        <div class="hero-image" style=" background-image: url({{post.image.url}})">

        </div>
        {% else %}
        <div class="hero-image" style=" background-image: url('')">

        </div>
        {% endif %}
        <h1 class="blog-title" style="text-align: center;">{{post.title}}</h1>
        <div class="content">
            <div class="card aurthor-info" style="width: 18rem;">
                {% if post.author.author.profile_pic %}
                <img src="{{post.author.author.profile_pic.url}}" class="card-img-top" alt="...">
                {% else %}
                <img src="{% static '/images/placeholder.png' %}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <p class="card-text" style="text-align: center;">
                        {{post.author.username}}<br>
                        {{post.author.email}}<br>
                        {{post.author.date_created}}
                    </p>
                </div>
              </div>
            <div class="content-text">
                {{post.body|safe}}
            </div>
        </div>

        <div class="comments-container">
            <form action="{% url 'blog:comment' post.id %}" method="POST" >
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" id="floatingInput" placeholder="comment" name="comment">
                    <label for="floatingInput">Write Your Comments Here...</label>
                </div>
                <button type="submit" class="btn btn-outline-primary btn-sm">Post</button>
            </form>
            {% for comment in comments %}
            <div class="card" style="margin-top:3vh">
                <div class="card-header">
                    {{comment.author}}
                </div>
                <div class="card-body">
                    <p class="card-text">{{comment.comment_text}}</p>
                    <span>{{comment.total_likes}}</span>
                    <a data-commentid={{comment.id}}  style="color: #3f3f3f; font-size: 20px; cursor: pointer;" class="likeBtn"><i class="far fa-thumbs-up"></i></a>

                </div>
            </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

blog/templates/blog/create_post.html
{% extends 'blog/main.html' %}
{% load static %}
{% block content %}
    <section class="blog-form-container">
        <div class="form-container">
            <form method="POST" action="{% url 'blog:create_post'%}"  enctype='multipart/form-data'>
                {% csrf_token %}
                {{form.media}}
                {{form.as_p}}
                <input type="submit" value="Create post" class="btn btn-outline-primary custom-btn">
            </form>
            </div>
            <div class="aurthor-info">
                <div class="profile-picture" style="background-image: url('{{user.author.profile_pic.url}}');">
            </div>
            <p>{{user.username}}</p>
            <p>{{user.email}}</p>
            <p>{{date_created}}</p>
        </div>
    </section>
{% endblock %}

blog/templates/blog/dashboard.html
{% extends 'blog/main.html'%}
{% load static %}
{% block content %}
    <div class="outer-profile-container">
        <div class="inner-profile-container">
            <div class="profile-detail-container">
                <div class="profile-picture" style="background-image: url('{{user.author.profile_pic.url}}');">
                </div>
                <h2>{{user.username}}</h2>
                <h3>{{user.email}}</h3>
            </div>
            <div class="total-post">
                <h3>Total Posts</h3>
                <p>{{total_posts}}</p>
            </div>
            <div class="total-feedbacks">
                <h3>Total Feedbacks</h3>
                <p>80</p>
            </div>
        </div>
    </div>
     <div class="form">
        <form action="{% url 'blog:update_profile_pic' %}" method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            {{form.as_p}}<br>
            <input type="submit" value="update" class="btn btn-outline-primary btn-lg">
        </form>
         <a href="{% url 'blog:create_post' %}"><button type="button" class="btn btn-outline-primary btn-lg">Create Post</button></a>
    </div>
    <div class="your-post">
        <h1>Your Posts</h1>
        {% for post in posts %}
        <div class="post-card">
            {% if post.image %}
            <div class="post-thumbnail" style="background-image: url('{{post.image.url}}');">
                
            </div>
            {% else %}
            <div class="post-thumbnail" style="background-image: url('');">

            </div>
            {% endif %}
            <div class="post-title">
                <p>{{post.title}}</p>
                <div class="buttons">
                    <a href="{% url 'blog:update_post' post.slang %}" class="btn btn-outline-primary" style="margin: 10px;">Update</a>
                    <a href="{% url 'blog:delete_post' post.slang %}" class="btn btn-outline-danger">Delete</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/main.html' %}

{% load static %}

{% block content %}
    <section class="main-container"> 
      <a href="#" style="text-decoration: none; color: #3F3F3F;"><div class="latest-container">
            <div class="latest-inner-container">
                <img src="{% static '/images/cover.jpg' %}" alt="">
                <div class="latest">
                    <h3>Latest</h3>
                    <h2>Learn to make yourself More Creative</h2>
                    <p>Explore yourself and discover yourself and make yourself more Creative</p>
                </div>
            </div>
        </div></a>
                <h3 style="text-align: center; font-size: 20px; margin-top: 2vh">Articles</h3>

        <div class="posts-container">
            {% for post in posts%}
            <div class="post">
                {% if post.image %}
                <div class="thumbnail" style=" background-image: url({{post.image.url}})">
                    <!-- background-image is previewed as thumbnail -->
                </div>
                {% else %}
                <div class="thumbnail" style=" background-image: url('')">
                    <!-- background-image is previewed as thumbnail -->
                </div>
                {% endif %}
                <div class="post-text">
                    <a href="{% url 'blog:article' post.slang %}"><h3>{{post.title}}</h3></a>
                </div>
            </div>
            {% endfor %}
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end">
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
              </li>
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item">
                <a class="page-link" href="#">Next</a>
              </li>
            </ul>
          </nav>
    </section>

{% endblock %}

blog/templates/blog/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/bb21c5ca37.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500;600&family=Rock+Salt&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/style/style.css' %}">
    <title>Readit</title>
    <script>
      user = "{{request.user}}"

      function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');

    </script>
</head>
<body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'blog:index' %}" style="font-family:Rock Salt, sans-serif; color:#5FBFE9;">ReadIt</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarTogglerDemo02" style="background-color: #f8f9fa; z-index:5">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:index'%}">Home</a>
      </li>
         <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="background-color: #fff; z-index: 3;">
            {% for category in categories %}
            <a class="dropdown-item" href="{% url 'blog:category' category.name %}">{{category.name}}</a>
            {% endfor %}
        </div>
      </li>
        {% if user.is_authenticated %}
            {% for group in user.groups.all %}
                {% if group.name == 'admin' %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:admin_dashboard'%}">Hello,{{user.first_name}}</a>
                  </li>
                {% else %}
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:dashboard'%}">Hello,{{user.first_name}}</a>
                  </li>
                {% endif %}
            {% endfor %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
          </li>

        {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:register' %}">Register</a>
      </li>
        {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'blog:search' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    {% block content %}

    {% endblock%}

<footer style="margin-top: 5vh">
    <div class="footer-container" >
        <img src="{% static '/images/logo.png' %}" alt="">
        <div class="footer-text">
            <table class="table" style=" color: #707070;">
                <tr>
                    <td>Home</td>
                    <td>Promotion</td>
                    <td>Facebook</td>
                </tr>
                <tr>
                    <td>About Us</td>
                    <td>Partners</td>
                    <td>Instagram</td>
                </tr>
                <tr>
                    <td>Direction</td>
                    <td>Career</td>
                    <td>Twiter</td>
                </tr>
                <tr>
                    <td></td>
                    <td>FAQs</td>
                    <td>Youtube</td>
                </tr>
            </table>
        </div>
    </div>
</footer> 
    <script src="{% static '/js/app.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/password_reset_complete.html
<div class="container p-4">
    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
    <hr>
    <p>Your password has been set. You may go ahead and log in now.</p>

    <a href="blog:login" class="btn btn-primary">Login</a>
</div>

blog/templates/blog/update_post.html
{% extends 'blog/main.html' %}
{% load static %}
{% block content %}
    <section class="blog-form-container">
        <div class="form-container">
            <form method="POST" action="{% url 'blog:update_post' post.slang %}"  enctype='multipart/form-data'>
                {% csrf_token %}
                {{form.media}}
                {{form.as_p}}
                <input type="submit" value="Update post" class="btn btn-outline-primary custom-btn">
            </form>
            </div>
            <div class="aurthor-info">
                <div class="profile-picture" style="background-image: url(./images/placeholder.png);">
            </div>
            <p>{{user.username}}</p>
            <p>{{user.email}}</p>
            <p>{{date_created}}</p>
        </div>
    </section>
{% endblock %}